server {
    listen 80;
    server_name _;
    client_max_body_size 10M;

    # Giao diện Landing Page (Frontend HTML)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ =404;
    }

    # API Proxy Routing (Chuyển tiếp ngầm sang Node.js)
    location /proxy {
        # proxy-gateway-node là tên container backend định nghĩa trong docker-compose
        proxy_pass http://proxy-gateway-node:3000/proxy;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Tính năng Health check cho API
    location /health {
        proxy_pass http://proxy-gateway-node:3000/health;
        proxy_set_header Host $host;
    }
}
